# Generated by Django 4.0.4 on 2022-05-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_menu_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя категории')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='slug')),
                ('cat_menu_name_image', models.ImageField(blank=True, null=True, upload_to='image/menu/%Y/%m/%d/', verbose_name='Фото категории меню')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['cat_menu_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_number', models.IntegerField(blank=True, max_length=13)),
                ('message', models.TextField(blank=True, verbose_name='Сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='BaseMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_menu', models.CharField(blank=True, max_length=40, null=True, verbose_name='Заголовок меню')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='slug')),
                ('text_menu', models.TextField(blank=True, null=True, verbose_name='Текст меню')),
                ('image_menu', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomad_Coffee_Naryn_app.catmenu', verbose_name='Категория')),
            ],
        ),
    ]
